# Generated by Django 3.2.5 on 2021-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210710_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='null', upload_to='videos/thumbnail/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
